### PR TITLE
Add docs and insta-Rust-to-WASM-compile

### PR DESCRIPTION
**Pull request by killercup**
Also introduces a glorious hack to enable literate programming, incl. a
currently unused function that generates modules one the fly (that
crashes with some internal node assertion error).

### CODE REVIEW

**Review by badboy — APPROVED** [review]

**Comment by badboy** [comment]
:shipit: 



bors r+

**Comment by killercup** [comment]
bors r-

added travis retry calls on master

**Comment by killercup** [comment]
and again!

bors r+

**Comment by killercup** [comment]
Ah, sorry bors, I didn't configure appveyor here.

bors r-

I'll not bother you further and just merge this myself.

**Pull request merged**
