### PR TITLE
Smaller WASM files are better WASM files

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by badboy** [comment]
What's removed by opt-level `s`?

**Comment by badboy** [comment]
I mean ... if it's better: bors r+

**Comment by killercup** [comment]
No clue what it does in detail, but it's "optimize for size". So probably less inlining and loop unrolling?

**Comment by killercup** [comment]
huh, you okay travis?

> oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"

bors r+

**Pull request merged**
